---
title: "Configuring Python Environment for Project"
output: 
  md_document:
    variant: gfm
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Assumes running Python code from within RStudio IDE.  Based on the documentation included [here](https://support.rstudio.com/hc/en-us/articles/360023654474-Installing-and-Configuring-Python-with-RStudio) and [here](https://support.rstudio.com/hc/en-us/articles/1500007929061-Using-Python-with-the-RStudio-IDE):

1.  Install [Anaconda](https://www.anaconda.com/distribution/) distribution of Python.
2. *In RStudio IDE*: Go to *Tools > Global Options > Python* and select Python interpreter.
2. *In Anaconda terminal*: Ensure that installation of Python has the virtualenv package installed by running: `pip install virtualenv`
2.  *In Anaconda terminal*: Navigate into RStudio project directory using: `cd "C:/Users/joshh/Documents/GitHub/trilogy"`
3.  *In Anaconda terminal*: Create new virtual environment in a folder called `my_env` within project directory using the following command: `virtualenv my_env`
4. *In RStudio console*: Install package `install.packages("reticulate")`
5.  *In RStudio IDE*: Configure `reticulate` to point to the Python executable in your `virtualenv` by creating an `.Rprofile` file in your project directory, with the following contents: `Sys.setenv(RETICULATE_PYTHON = "my_env/bin/python")`
6.  *In RStudio terminal*: Install packages `pip install numpy pandas matplotlib spacy pytextrank gensim notebook stanza spacy_stanza`
7.  *In RStudio terminal*: Load English tokenizer, tagger, parser and NER with `python -m spacy download en_core_web_sm`
